// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _24x0.Context;

#nullable disable

namespace _24x0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605033946_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_24x0.Model.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TemporadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("_24x0.Model.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("_24x0.Model.Piloto", b =>
                {
                    b.HasOne("_24x0.Model.Temporada", null)
                        .WithMany("GridDisponivel")
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("_24x0.Model.Temporada", b =>
                {
                    b.Navigation("GridDisponivel");
                });
#pragma warning restore 612, 618
        }
    }
}
