// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _24x0.Context;

#nullable disable

namespace _24x0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605034125_Corrigindo")]
    partial class Corrigindo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_24x0.Model.Construtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Construtores");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoConstrutora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("ConstrutorId")
                        .HasColumnType("integer");

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer");

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstrutorId");

                    b.ToTable("DesempenhoConstrutoras");
                });

            modelBuilder.Entity("_24x0.Model.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TemporadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("_24x0.Model.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoConstrutora", b =>
                {
                    b.HasOne("_24x0.Model.Construtor", "Construtor")
                        .WithMany("Historico")
                        .HasForeignKey("ConstrutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Construtor");
                });

            modelBuilder.Entity("_24x0.Model.Piloto", b =>
                {
                    b.HasOne("_24x0.Model.Temporada", null)
                        .WithMany("GridDisponivel")
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("_24x0.Model.Construtor", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("_24x0.Model.Temporada", b =>
                {
                    b.Navigation("GridDisponivel");
                });
#pragma warning restore 612, 618
        }
    }
}
