// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _24x0.Context;

#nullable disable

namespace _24x0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606170837_AddDesempenhos")]
    partial class AddDesempenhos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_24x0.Model.Construtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Construtores");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoConstrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("ConstrutorId")
                        .HasColumnType("integer");

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.Property<double>("Pontos")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConstrutorId");

                    b.ToTable("DesempenhosConstructor");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoPiloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.Property<int>("PilotoId")
                        .HasColumnType("integer");

                    b.Property<double>("Pontos")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PilotoId");

                    b.ToTable("DesempenhosPiloto");
                });

            modelBuilder.Entity("_24x0.Model.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ForcaBase")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoConstrutor", b =>
                {
                    b.HasOne("_24x0.Model.Construtor", "Construtor")
                        .WithMany()
                        .HasForeignKey("ConstrutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Construtor");
                });

            modelBuilder.Entity("_24x0.Model.DesempenhoPiloto", b =>
                {
                    b.HasOne("_24x0.Model.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piloto");
                });
#pragma warning restore 612, 618
        }
    }
}
